version: 0.2

env:
    variables:
        IMAGE_TAG: 1.0.0

phases:
    pre_build:
        commands:
            - aws --version
            - echo ${DOCKER_HUB_PASSWORD} | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    build:
        commands:
            - make IMAGE_TAG=${IMAGE_TAG} TARGET=publish
