version: 0.2

phases:
    pre_build:
        commands:
            - aws --version
            - echo ${DOCKER_HUB_PASSWORD} | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    build:
        commands:
            - make TARGET=publish SAM_ARTIFACTS_BUCKET=${SAM_ARTIFACTS_BUCKET}
artifacts:
    files:
        - platforms/php/php-lambda/sam-output.yaml
    discard-paths: yes