AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This SAM Application provides the base Lambda Layer to run PHP projects as Lambda Functions

Metadata:
  AWS::ServerlessRepo::Application:
    Name: php-74-runtime
    Description: This SAM Application provides the base Lambda Layer to run PHP projects as Lambda Functions
    Author: gbmcarlos
    SpdxLicenseId: MIT
    LicenseUrl: ./aws-sar/LICENSE.txt
    ReadmeUrl: ./aws-sar/README.md
    HomePageUrl: https://github.com/gbmcarlos/php-stack
    SourceCodeUrl: https://github.com/gbmcarlos/php-stack
    SemanticVersion: '0.2.0'

Resources:
  Php74RuntimeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: php-74-runtime
      Description: This layer provides a PHP 7.4 runtime
      CompatibleRuntimes:
        - provided
      ContentUri: ./php-runtime.zip
  Php74RuntimeLayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: php-74-runtime-layer
      Type: String
      Value: !Ref Php74RuntimeLayer
Outputs:
  PhpBinLayerArn:
    Value: !Ref Php74RuntimeLayerParameter
    Description: ARN of the PHP 7.4 runtime layer
